# Generated by Django 4.2 on 2023-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("craft", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
