# Generated by Django 4.2 on 2023-04-21 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("craft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
    ]
