# Generated by Django 4.2 on 2023-04-30 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("craft", "0002_alter_order_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="in_stock",
        ),
    ]
