version: "3"

services:
  backend:
    build: ./
    container_name: craft_container
    working_dir: /craft
    command:
      - ./commands/start_server.sh
    ports:
      - 8010:8000
    volumes:
      - ./src:/craft/src
      - ./commands:/craft/commands
    env_file:
      - .env
